id = "zed-gilt"
name = "Gilt Language Support"
version = "0.1.0"
schema_version = 1
authors = ["Stargrazer Games"]
description = "Safe modding language for Kingdoms Game"
repository = "https://github.com/luckybelcik/gilt"

[grammars.gilt]
repository = "https://github.com/luckybelcik/gilt"
commit = "main"
path = "tree-sitter-gilt"
